### ISSUE TITLE
trouble finding FrontEnds.xml on Ubuntu

### ISSUE THREAD

**Issue by orcronomicon** [Manawyrm/sdrsharp-plutosdr#15]
I have SDRSharp running through Mono on the new Ubuntu release but I cannot locate any XML files to update. I am unsure of what is different between the Linux and Windows installation. I am fairly new to Linux, Xamarin/Mono, and SDRSharp. Is there an easy solution for this?

-edit: The linux version on github is out of date and does not have any XML files, says its version 0.0.0.0. I will need to get a newer version going here that includes an xml to edit.

**Comment by Manawyrm** [comment]
Sorry for not answering quicker.

Yeah, the SDR# versions that run on Mono are either really old or pretty broken. 
I am using Linux as my main OS, too. Unfortunatly SDR# isn't really working all to well there. 
For SDR things I use a QEMU/libvirt VM and connect to the PlutoSDR via network (USB ethernet card via USB-OTG adapter). 

Even if you could maybe get an up-to-date version up-and-running, atleast under Mono you won't be able to use the PlutoSDR, because it uses native Windows libraries from Analog Devices. Mono can't run these. 
Wine might be able to (network only, no way USB is going to work), but the performance will be crap. 

So yeah, for now I'd suggest using a VM and network connect to the PlutoSDR.

**Comment by orcronomicon** [comment]
Thanks for this reply. Is Qemu your preference for virtualization or would there be benefits to using this over something like Virtualbox?
